//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdMeStore.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content_Approvals
    {
        public int Id_content { get; set; }
        public Nullable<int> Id_media { get; set; }
        public Nullable<int> Id_client { get; set; }
        public string Status { get; set; }
        public string Comment { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Medium Medium { get; set; }
    }
}
