//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdMeStore.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medium
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medium()
        {
            this.Content_Approvals = new HashSet<Content_Approvals>();
        }
    
        public int Id_media { get; set; }
        public Nullable<int> Id_project { get; set; }
        public byte[] Image { get; set; }
        public string Name_media { get; set; }
        public Nullable<int> Id_user { get; set; }
        public Nullable<int> Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Content_Approvals> Content_Approvals { get; set; }
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}
