//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdMeStore.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metric
    {
        public int Id_metric { get; set; }
        public Nullable<int> Id_project { get; set; }
        public string Type { get; set; }
        public Nullable<int> Value { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Goal { get; set; }
        public Nullable<int> Itog { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
