//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdMeStore.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int Id_report { get; set; }
        public Nullable<int> Id_project { get; set; }
        public string Type_report { get; set; }
        public Nullable<System.DateTime> Date_report { get; set; }
        public Nullable<int> Profit { get; set; }
        public Nullable<int> Expense { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
