//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdMeStore.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Id_request { get; set; }
        public Nullable<int> Id_client { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Request_date { get; set; }
        public Nullable<System.DateTime> Start_zapuska { get; set; }
        public Nullable<System.DateTime> End_zapuska { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
