//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdMeStore.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Id_Us_Proj { get; set; }
        public Nullable<int> Id_project { get; set; }
        public Nullable<int> Id_user { get; set; }
        public string Name_task { get; set; }
        public Nullable<System.DateTime> Srok { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}
